# Generated by Django 5.2.5 on 2026-01-02 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_chatsession_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatSession',
        ),
    ]
