# Generated by Django 5.2.5 on 2025-10-09 04:38

import apps.utils.enum_type
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_center', '0002_imagesport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportfield',
            name='sport_type',
            field=models.CharField(choices=[('FOOTBALL', 'FOOTBALL'), ('BADMINTON', 'BADMINTON'), ('TENNIS', 'TENNIS'), ('PICK_A_BALL', 'PICK_A_BALL')], default=apps.utils.enum_type.SportTypeEnum['FOOTBALL'], max_length=255),
        ),
    ]
