# Generated by Django 5.2.5 on 2025-10-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_center', '0003_alter_sportfield_sport_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesport',
            name='preview',
            field=models.ImageField(null=True, upload_to='images/preview/'),
        ),
        migrations.AlterField(
            model_name='sportfield',
            name='price',
            field=models.FloatField(blank=True),
        ),
    ]
