# Generated by Django 5.2.5 on 2025-11-22 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_center', '0005_alter_sportfield_sport_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportfield',
            name='sport_center',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='sport_center.sportcenter'),
        ),
    ]
