# Generated by Django 5.2.5 on 2025-10-16 04:18

import apps.utils.enum_type
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('CONFIRMED', 'CONFIRMED'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED')], default=apps.utils.enum_type.StatusBookingEnum['PENDING'], max_length=255),
        ),
    ]
